### ISSUE TITLE
SmartHUDReheated 3.2.0 Crash on world load

### ISSUE THREAD

**Issue by RubyRezal** [DeflatedPickle/SmartHUDReheated#3]
Minecraft 1.18.1
Fabric 0.12.12
SmartHUDReheated 3.2.0
+many other mods

Updating a modpack to include SmartHUDReheated. I've been testing ok with version 3.0.1 but when I updated to 3.2.0 the client crashes immediately on world load.  Rolling back to 3.0.1 seems to resolve the problem.

3.2.0 appears to load fine in isolation.  There may be a conflict with one of the many other mods in the modpack, but I can't seem to find where the conflict might be in the crash log.

[crash-2022-01-07_10.08.06-client.txt](https://github.com/DeflatedPickle/SmartHUDReheated/files/7829668/crash-2022-01-07_10.08.06-client.txt)

**Comment by Xastabus** [comment]
I'm sorry the information I gave probably wasn't very helpful.  I see you labeled this "wontfix" and closed it.  Did you determine the cause of the problem?
