### ISSUE TITLE
Game crash when connecting to 1.8 server with multiconnect

### ISSUE THREAD

**Issue by REALMWTH** [DeflatedPickle/SmartHUDReheated#6]
Removing this mod and/or connecting to 1.18.1 server resolves issue,
Using multiconnect version 1.5.10
[crash-2022-01-31_04.35.37-client.txt](https://github.com/DeflatedPickle/SmartHUDReheated/files/7967732/crash-2022-01-31_04.35.37-client.txt)

**Comment by REALMWTH** [comment]
@DeflatedPickle do you need any extra information? Why you've marked this as invalid?

My client version is 1.18.1, but I am using Multiconnect mod that modifies protocol version so I can connect to 1.8-1.18.1 servers.
Connecting to 1.8 server crashes the game as described above, while connecting to 1.18.1 server works fine.
I don't see a reason why client-side HUD mod wouldn't work but a bug.

**Comment by DeflatedPickle** [comment]
It's probably related to classes in the config not existing or being named something else. But I have no desire to support connecting to older versions. If anyone wants to fork and support that, they can. The license allows for it
